language: python

python:
    - "3.6"
    - "3.7"

before_install:
    - sudo apt-get -y install libblas-dev liblapack-dev

install:
    - pip install -r requirements.txt

script:
    - pytest --durations=0
    - cd example; bash run.sh
    - cd ..
    - cd doc; make html; cd ..

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $github_token
    local_dir: doc/html
    verbose: true
    on:
        branch: master
