name: ci
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    name: test
    steps:
      - name: install openblas
        run: |
            sudo apt-get update
            sudo apt-get -y install libblas-dev liblapack-dev
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
          cache: "pip"
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt
      - name: test scripts
        run: |
          pip install pytest-xdist pytest-cov
          export RENO_NUM_THREADS=1
          pytest -n 4 --durations=0 --cov=renormalizer
          pip install primme==3.2.*
          pytest --durations=0 renormalizer/mps/tests/test_gs.py::test_multistate --cov=renormalizer --cov-append
      - name: run examples
        run: |
            cd example; bash run.sh
            cd ..
      - name: test build doc
        run: |
          cd doc
          make html
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
